### ISSUE TITLE
Pruebas Navegadores

### ISSUE THREAD

**Issue by Sao912** [ISWPOLI/precise_estimate#102]
- [x]  Creación
- [x] Ejecución
- [x]  Validación
- [x]  Resolución

**Comment by Jwilchez** [comment]
Se presentan errores en las funciones de calendario en Firefox.
Se presentan errores de login en Chrome. Se necesita una extension adicional para el navegador.
Se presentan errores en los banner laterales en ambos navegadores ya que cuando se coloca un tamaño de ventana menor no muestra algunos titulos.
https://github.com/ISWPOLI/precise_estimate/commit/e1b469136258c323b9c9b33c678ff0f106f4befa
https://github.com/ISWPOLI/precise_estimate/commit/fb2da108b1a9a5c5730fc5d0755a97bf68adf1a1
https://github.com/ISWPOLI/precise_estimate/commit/218c58b2f39e7667c607f8bbd23b84500120cc2d
