### ISSUE TITLE
Prueba de carga y estres

### ISSUE THREAD

**Issue by Sao912** [ISWPOLI/precise_estimate#104]
- [x]  Creación
- [x] Ejecución
- [x]  Validación
- [x]  Resolución

**Comment by jjisazam** [comment]
En esta prueba se realizó 100 peticiones con 10 concurrencias arrojando los siguientes resultados:
•	Se llegó a tener un máximo de 1223 solicitudes hacia el servidor de manera satisfactoria en un tiempo de 2.3 segundos sin fallas.
•	Mínima: 172 ms
•	Media:226ms 
•	Mediana:213 ms
•	Máxima:1223 ms
![pruebas-no funcionales-100-10](https://cloud.githubusercontent.com/assets/20825918/26027300/3f8f1386-37d1-11e7-80dd-dcfe6309ad94.png)

**Comment by jjisazam** [comment]
Commit
7cd68e0
