### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by felipecanol** [ISWPOLI/precise_estimate#41]
- Requerimientos
    - [ ] Modelado del Canvas @felipecanol  
    - [ ] Objetivos del SMART @jjisazam
    - [ ] Requerimientos funcionales @Jwilchez 
    - [ ] Requerimientos no funcionales @Jwilchez 
    - [ ] Modelado de Casos de Uso + Fichas @Jwilchez 
    - [ ] Diagrama de Clases @felipecanol 
    - [ ] Diagrama de Secuencias @felipecanol 
    - [ ] Diagrama de Navegación Mockups @Sao912  

- Planeación
    - [ ] Selección de Metodologia @jjisazam
    - [ ] HistoryMap @jjisazam
    - [ ] Estimación Puntos por Función @Sao912 
    - [ ] Perfilado del Equipo de Trabajo @jjisazam
    - [ ] BurnDown chart Seguimiento de actividades (Reportes de velocidad de código) @felipecanol    @Sao912 @Jwilchez @jjisazam

- Diseño
    - [ ] Diagrama de Infraestrucutura @jjisazam
    - [ ] Diagrama de capas –diagrama componentes @jjisazam 
    - [ ] De Conectores, Interfaces (protocolos-Tivadis) @felipecanol 
    - [ ] De las Herramientas y frameworks @felipecanol 
 - Patrones de Diseño 
    - [ ] Explicación @jjisazam @felipecanol @Sao912 @Jwilchez 
    - [ ] Diagrama UML de patrones @jjisazam @felipecanol @Sao912 @Jwilchez 
- Pruebas
    - [ ] Plan de Pruebas @jjisazam @felipecanol @Sao912 @Jwilchez 
    - [ ] Pruebas Unitarias @jjisazam @felipecanol @Sao912 @Jwilchez 
    - [ ] Documentación del Código fuente. @jjisazam @felipecanol @Sao912 @Jwilchez 
    - [ ] Logs de Pruebas. @jjisazam @felipecanol @Sao912 @Jwilchez

**Comment by jjisazam** [comment]
Commit:
 7cd68e0
