### ISSUE TITLE
Pruebas CRUD Epica

### ISSUE THREAD

**Issue by Sao912** [ISWPOLI/precise_estimate#97]
- [x]  Creación
- [x] Ejecución
- [x]  Validación
- [x]  Resolución

**Comment by Jwilchez** [comment]
Creacion de Escenario de pruebas de epicas
[](https://documenter.getpostman.com/collection/view/2048860-4a7f5fb6-fd08-7b72-d6bc-0294eed8788a#482dc61b-9109-6aac-1c3e-503f1eeded33)
Ejecucion de pruebas de epicas
Validacion de primeras pruebas
Resolucion de errores de historias

**Comment by jjisazam** [comment]
Commit
bb0030c
